### ISSUE TITLE
Use of CATT in the computer cluster with Singularity tool

### ISSUE THREAD

**Issue by liyongzheng1** [GuoBioinfoLab/CATT#4]
Hello,
I want to run CATT in the computer cluster, because I am not familiar with Julia, so I have chosen to run it in Docker, however, the cluster doesn't support Docker, but supports Singularity. After build image with command "singularity build CATT.sif docker://guobioinfolab/catt:latest”，I use the command " /path/to/CATT.sif catt -h" to test whether it works, as so far, everything is OK, but when I try to run test example "/path/to/CATT.sif catt -f testSample.fq -o testSampleOutput",  it raise the error "
Traceback (most recent call last):
  File "/usr/bin/catt", line 48, in <module>
    with open("/home/feifei/config.jl", "w") as handle:
IOError: [Errno 30] Read-only file system: '/home/feifei/config.jl' "
I try to change the file permission in the image, it is failed.
Could you give me some advice to address this problem? 
Thanks!

System : CentOS Linux release 7.7.1908 (Core)
Singularity version: 3.2.0

**Comment by chunjie-sam-liu** [comment]
Try map /home/feifei:/your-writable-path.

**Comment by liyongzheng1** [comment]
@chunjie-sam-liu 
I try  it, however, there is a new error "/.singularity.d/runscript: 39: exec: catt: not found"
the command I used is "singularity run --bind $PWD:/home/feifei CATT.sif catt -h"

**Comment by aqzas** [comment]
@liyongzheng1 
The first error raised because of the file permission and the second error raised due to can't find the the program 'catt' (which located in /home/feifei/), which, should be already set up in the Docker image,  so it might due to the different behavior between docker and Singularity (permission, path, BLAHBLAH). 
As we are not familiar with Singularity,  the recommended way is installing CATT by source code
